services:
  discord-bot:
    build: .
    restart: always
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATA_FOLDER=${DATA_FOLDER}
      - PREFIX=${PREFIX}
      - TOKEN=${TOKEN}
      - CURR_EVENT=${CURR_EVENT}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - PIXIV_REFRESH_TOKEN=${PIXIV_REFRESH_TOKEN}
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 30514:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}